# This is a POC for a triple solution pipeline
trigger: none

resources:
  repositories:
  - repository: EZWM
    type: github
    endpoint: adriansuhov
    name: adriansuhov/azure-functions-1
    trigger:
      batch: true
      branches:
        include:
        - main

  - repository: Customer
    type: github
    endpoint: adriansuhov
    name: adriansuhov/azure-functions-2
    trigger:
      batch: true
      branches:
        include:
        - main

  - repository: Convacloud
    endpoint: adriansuhov
    type: github
    name: adriansuhov/azure-functions-3
    trigger:
      batch: true
      branches:
        include:
        - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: EZWM
- checkout: Customer
- checkout: Convacloud