name: Adsuho jFrog deploy

on:
  [push]

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_FUNCTIONAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_FUNCTIONAPP_NAME: adsuhoJfrog  # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'Function-AdsuhojFROG/'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'                     # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master
      
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v1
      env:
        JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_SECRET_1 }}
      
    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'npm'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        npm install
        npm run build --if-present
        npm run test --if-present 
        popd

    # 2. Change these variables for your configuration:
    - name: 'Upload using NPM'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        # jfrog rt dl demo-npm-local/
        # jfrog rt u . demo-npm-local/
        # jfrog rt u . demo-npm-local/jfrog-function-1.0.0
        popd
   
    - name: 'Upload using jFrog'
      run: |
        jfrog rt u ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} demo-npm-local/v1.0.0.0001

    # - name: 'Run Azure Functions Action'
    #   uses: Azure/functions-action@v1
    #   id: fa
    #   with:
    #     app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
    #     package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
    #     publish-profile: ${{ secrets.ADSUHOJFROG_FUNCTIONAPP_PUBLISH_PROFILE }}
        
